version: '3.3'

services:

  ###### EPP #######
  epp_app:
    build:
      context: ../
      dockerfile: demo/epp/${APP_DIST:-centos7}/Dockerfile
    environment:
      DB_HOST: epp_db
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      LOGSTASH_HOST: logstash
      LOGSTASH_PORT: 5000
    volumes:
      - $ESS_CONFIGS:/src/ess_configs:ro
      - $ESS_DATA:/ESSArch
    ports:
      - 8002:8000
    depends_on:
      - epp_db
      - rabbitmq
      - redis
      - elasticsearch
      - logstash
    networks:
      - ess

  epp_celery_beat:
    build:
      context: ../
      dockerfile: demo/epp/${APP_DIST:-centos7}/Dockerfile
    command:
      - /bin/bash
      - -c
      - |
        while ! nc -z epp_app 8000; do echo "waiting for epp_app..."; sleep 3; done
        celery -A config beat --loglevel=info
    environment:
      DB_HOST: epp_db
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      LOGSTASH_HOST: logstash
      LOGSTASH_PORT: 5000
    volumes:
      - $ESS_CONFIGS:/src/ess_configs:ro
      - $ESS_DATA:/ESSArch
    depends_on:
      - epp_db
      - redis
      - rabbitmq
      - elasticsearch
      - logstash
    networks:
      - ess

  epp_celery_worker:
    build:
      context: ../
      dockerfile: demo/epp/${APP_DIST:-centos7}/Dockerfile
    command:
      - /bin/bash
      - -c
      - |
        while ! nc -z epp_app 8000; do echo "waiting for epp_app..."; sleep 3; done
        celery -A config worker --loglevel=info --concurrency=5 -Ofair -Q celery,validation,file_operation,pollers
    environment:
      DB_HOST: epp_db
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      LOGSTASH_HOST: logstash
      LOGSTASH_PORT: 5000
    volumes:
      - $ESS_CONFIGS:/src/ess_configs:ro
      - $ESS_DATA:/ESSArch
    depends_on:
      - epp_db
      - redis
      - rabbitmq
      - elasticsearch
      - logstash
    networks:
      - ess

  epp_db:
    image: "postgres:$POSTGRES_VERSION"
    environment:
      POSTGRES_DB: epp
      POSTGRES_USER: arkiv
      POSTGRES_PASSWORD: password
    ports:
      - 3003:5432
    networks:
      - ess


  ###### ETA #######
  eta_app:
    build:
      context: ../
      dockerfile: demo/eta/${APP_DIST:-centos7}/Dockerfile
    environment:
      DB_HOST: eta_db
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      LOGSTASH_HOST: logstash
      LOGSTASH_PORT: 5000
    volumes:
      - $ESS_CONFIGS:/src/ess_configs:ro
      - $ESS_DATA:/ESSArch
    ports:
      - 8001:8000
    depends_on:
      - eta_db
      - rabbitmq
      - redis
      - elasticsearch
      - logstash
    networks:
      - ess

  eta_celery_worker:
    build:
      context: ../
      dockerfile: demo/eta/${APP_DIST:-centos7}/Dockerfile
    command:
      - /bin/bash
      - -c
      - |
        while ! nc -z eta_app 8000; do echo "waiting for eta_app..."; sleep 3; done
        celery -A config worker --loglevel=info --concurrency=5 -Ofair -Q celery,validation,file_operation,pollers
    environment:
      DB_HOST: eta_db
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      LOGSTASH_HOST: logstash
      LOGSTASH_PORT: 5000
    volumes:
      - $ESS_CONFIGS:/src/ess_configs:ro
      - $ESS_DATA:/ESSArch
    depends_on:
      - eta_db
      - redis
      - rabbitmq
      - elasticsearch
      - logstash
    networks:
      - ess

  eta_db:
    image: "postgres:$POSTGRES_VERSION"
    ports:
      - 3002:5432
    environment:
      POSTGRES_DB: eta
      POSTGRES_USER: arkiv
      POSTGRES_PASSWORD: password
    networks:
      - ess


  ###### ETP #######
  etp_app:
    build:
      context: ../
      dockerfile: demo/etp/${APP_DIST:-centos7}/Dockerfile
    environment:
      DB_HOST: etp_db
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      LOGSTASH_HOST: logstash
      LOGSTASH_PORT: 5000
    volumes:
      - $ESS_CONFIGS:/src/ess_configs:ro
      - $ESS_DATA:/ESSArch
    ports:
      - 8000:8000
    depends_on:
      - etp_db
      - rabbitmq
      - redis
      - elasticsearch
      - logstash
    networks:
      - ess

  etp_celery_worker:
    build:
      context: ../
      dockerfile: demo/etp/${APP_DIST:-centos7}/Dockerfile
    command:
      - /bin/bash
      - -c
      - |
        while ! nc -z etp_app 8000; do echo "waiting for etp_app..."; sleep 3; done
        celery -A config worker --loglevel=info --concurrency=5 -Ofair -Q celery,validation,file_operation,pollers
    environment:
      DB_HOST: etp_db
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      LOGSTASH_HOST: logstash
      LOGSTASH_PORT: 5000
    volumes:
      - $ESS_CONFIGS:/src/ess_configs:ro
      - $ESS_DATA:/ESSArch
    depends_on:
      - etp_db
      - redis
      - rabbitmq
      - elasticsearch
      - logstash
    networks:
      - ess

  etp_db:
    image: "postgres:$POSTGRES_VERSION"
    ports:
      - 3001:5432
    environment:
      POSTGRES_DB: etp
      POSTGRES_USER: arkiv
      POSTGRES_PASSWORD: password
    networks:
      - ess


  ###### Shared services ######
  redis:
    image: "redis:$REDIS_VERSION"
    ports:
      - 6379:6379
    networks:
      - ess

  rabbitmq:
    image: "rabbitmq:$RABBITMQ_VERSION"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    volumes:
      - $ESS_CONFIGS/dockerfiles/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
      - ess


  ###### ELK Stack #######
  elasticsearch:
    build:
      context: ../dockerfiles/elasticsearch
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ../dockerfiles/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - ess

  logstash:
    build:
      context: ../dockerfiles/logstash
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ../dockerfiles/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ../dockerfiles/logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    networks:
      - ess

  kibana:
    build:
      context: ../dockerfiles/kibana
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ../dockerfiles/kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - ess

networks:
  ess:
    driver: bridge
